<?php
session_start();
ob_start();
date_default_timezone_set('Asia/Ho_Chi_Minh');
require('../config.php');
i_func('db');

$arr = array(
    array('Products','Các sản phẩm','Products','제품','制品'),
    array('PhamXuanDong','Phạm Xuân Đồng','Pham Xuan Dong','팜 법사 동','范董璇'),
    array('SystemUpdate','cập nhật hệ thống','System Update','시스템 업데이트','系统更新'),
    array('CreateNew','Tạo mới','Create New','새로 만들기','创建新的'),
    array('UsersId','Id người dùng','Users Id','사용자 아이디','用户标识'),
    array('UsersName','người dùng Tên','Users Name','사용자 이름','用户名'),
    array('UsersFullName','Người dùng Họ và tên','Users Full Name','사용자 전체 이름','用户全名'),
    array('UsersPassword','người dùng Mật khẩu','Users Password','사용자 암호','用户密码'),
    array('UsersEmail','người dùng Email','Users Email','사용자 이메일','用户电子邮件'),
    array('UsersOption','người dùng lựa chọn','Users Option','사용자 옵션','用户选项'),
    array('UsersCreateDate','Người dùng Tạo ngày','Users Create Date','사용자 생성 날짜','用户创建日期'),
    array('UsersUpdateDate','Người dùng Cập nhật ngày','Users Update Date','사용자 업데이트 날짜','用户更新日期'),
    array('CompanyId','Id Công ty','Company Id','회사 아이디','公司标识'),
    array('CompanyName','Tên công ty','Company Name','회사 이름','公司名'),
    array('CompanyInformation','Thông tin công ty','Company Information','회사 정보','公司信息'),
    array('CompanyDescription','Thông tin công ty','Company Description','회사 설명','公司介绍'),
    array('CompanyOption','Lựa chọn công ty','Company Option','회사 옵션','公司期权'),
    array('CompanyCreateDate','Công ty Tạo ngày','Company Create Date','회사는 생성 날짜','公司创建日期'),
    array('CompanyUpdateDate','Công ty Cập nhật ngày','Company Update Date','회사 업데이트 날짜','公司更新日期'),
    array('DivisionsId','Id chia rẽ','Divisions Id','사단의 아이디','部门标识'),
    array('DivisionsName','chia rẽ Tên','Divisions Name','부서 이름','部门名称'),
    array('DivisionsInformation','Thông tin các đơn vị','Divisions Information','사단 정보','部门信息'),
    array('DivisionsDescription','bộ phận Mô tả','Divisions Description','사단 설명','部门说明'),
    array('DivisionsOption','bộ phận Lựa chọn','Divisions Option','사단 옵션','部门选项'),
    array('DivisionsCreateDate','Bộ phận Tạo ngày','Divisions Create Date','사단은 생성 날짜','部门创建日期'),
    array('DivisionsUpdateDate','Bộ phận Cập nhật ngày','Divisions Update Date','사단 업데이트 날짜','分部更新日期'),
    array('TeamsId','Id đội','Teams Id','팀 아이디','团队标识'),
    array('TeamsName','đội Tên','Teams Name','팀 이름','团队名称'),
    array('TeamsInformation','đội Thông tin','Teams Information','팀 정보','团队信息'),
    array('TeamsDescription','đội Mô tả','Teams Description','팀 설명','团队介绍'),
    array('TeamsOption','đội Tùy chọn','Teams Option','팀 옵션','球队选项'),
    array('TeamsCreateDate','Đội Tạo ngày','Teams Create Date','팀은 날짜 만들기','团队创建日期'),
    array('TeamsUpdateDate','Đội Cập nhật ngày','Teams Update Date','팀 업데이트 날짜','团队更新日期'),
    array('PartsId','Id phần','Parts Id','부품 아이디','部件ID'),
    array('PartsName','Tên bộ phận','Parts Name','부품 이름','零部件名称'),
    array('PartsInformation','Thông tin phụ tùng','Parts Information','부품 정보','配件信息'),
    array('PartsDescription','phần Mô tả','Parts Description','부품 설명','部件说明'),
    array('PartsOption','phần Tùy chọn','Parts Option','부품 옵션','配件选择'),
    array('PartsCreateDate','Phần Tạo ngày','Parts Create Date','부품 생성 날짜','部件创建日期'),
    array('PartsUpdateDate','Phụ tùng Cập nhật ngày','Parts Update Date','부품 업데이트 날짜','配件更新日期'),
    array('SectionId','Id phần','Section Id','제 아이디','截面号'),
    array('SectionName','Section Name','Section Name','제 이름','部分名称'),
    array('SectionInformation','Mục Thông tin','Section Information','제 정보','部分信息'),
    array('SectionDescription','Mục Mô tả','Section Description','섹션 설명','部分说明'),
    array('SectionOption','Mục Tùy chọn','Section Option','섹션 옵션','部分的选项'),
    array('SectionCreateDate','Mục Tạo ngày','Section Create Date','제 날짜 만들기','科创建日期'),
    array('SectionUpdateDate','Mục Cập nhật ngày','Section Update Date','제 업데이트 날짜','部分更新日期'),
    array('AssemblyLineId','Id Dây chuyền sản xuất','Assembly Line Id','조립 라인 아이디','装配生产线标识'),
    array('AssemblyLineName','Hội Tên Dòng','Assembly Line Name','조립 라인 이름','装配生产线名称'),
    array('AssemblyLineInformation','Hội Đường Dây Thông Tin','Assembly Line Information','조립 라인 정보','装配线信息'),
    array('AssemblyLineDescription','Dây chuyền lắp ráp Mô tả','Assembly Line Description','조립 라인 설명','装配线说明'),
    array('AssemblyLineOption','Dây chuyền lắp ráp Tùy chọn','Assembly Line Option','조립 라인 옵션','装配线选项'),
    array('AssemblyLineCreateDate','Dây chuyền lắp ráp Tạo ngày','Assembly Line Create Date','조립 라인은 날짜 만들기','装配线创建日期'),
    array('AssemblyLineUpdateDate','Dây chuyền lắp ráp Cập nhật ngày','Assembly Line Update Date','조립 라인 업데이트 날짜','装配线更新日期'),
    array('StationsId','Id trạm','Stations Id','스테이션 아이디','站标识'),
    array('StationsName','trạm Tên','Stations Name','역 이름','站名'),
    array('StationsInformation','trạm thông tin','Stations Information','역 정보','站的信息'),
    array('StationsDescription','trạm Mô tả','Stations Description','스테이션 설명','站说明'),
    array('StationsOption','trạm Tùy chọn','Stations Option','스테이션 옵션','站选项'),
    array('StationsCreateDate','Trạm Tạo ngày','Stations Create Date','스테이션은 날짜 만들기','站创建日期'),
    array('StationsUpdateDate','Trạm Cập nhật ngày','Stations Update Date','스테이션 업데이트 날짜','站更新日期'),
    array('MachinesId','Id máy','Machines Id','기계 아이디','机器编号'),
    array('MachinesName','máy móc Tên','Machines Name','기계 이름','机器名称'),
    array('MachinesInformation','Thông tin máy','Machines Information','기계 정보','机的信息'),
    array('MachinesDescription','Mô tả máy','Machines Description','기계 설명','机器说明'),
    array('MachinesOption','máy móc Tùy chọn','Machines Option','기계 옵션','机选'),
    array('MachinesCreateDate','Máy Tạo ngày','Machines Create Date','기계 날짜를 만들기','机创建日期'),
    array('MachinesUpdateDate','Máy móc Cập nhật ngày','Machines Update Date','기계 업데이트 날짜','机更新日期'),
    array('ModelsId','Id Models','Models Id','모델 아이디','型号标识'),
    array('ModelsName','mô hình Tên','Models Name','모델 이름','车型名称'),
    array('ModelsInformation','Thông tin mô hình','Models Information','모델 정보','车型信息'),
    array('ModelsDescription','mô hình mô tả','Models Description','모델 설명','车型介绍'),
    array('ModelsOption','mô hình Tùy chọn','Models Option','모델 옵션','模型选项'),
    array('ModelsCreateDate','Mô hình Tạo ngày','Models Create Date','모델 생성 날짜','模型创建日期'),
    array('ModelsUpdateDate','Mô hình Cập nhật ngày','Models Update Date','모델 업데이트 날짜','车型更新日期'),
    array('ShiftId','chuyển Id','Shift Id','이드 시프트','按住Shift键标识'),
    array('ShiftName','Tên phím shift','Shift Name','시프트 이름','班次名称'),
    array('ShiftInformation','Thông tin thay đổi','Shift Information','쉬프트 정보','班信息'),
    array('ShiftDescription','thay đổi Mô tả','Shift Description','시프트 설명','移说明'),
    array('ShiftOption','thay đổi lựa chọn','Shift Option','시프트 옵션','转向选项'),
    array('ShiftCreateDate','Shift để tạo ngày','Shift Create Date','날짜를 만들기 Shift 키','按住Shift键创建日期'),
    array('ShiftUpdateDate','Chuyển Cập nhật ngày','Shift Update Date','업데이트 날짜 시프트','移更新日期'),
    array('ProductsId','Id sản phẩm','Products Id','제품 아이디','产品编号'),
    array('ProductsName','Tên sản phẩm','Products Name','제품 이름','产品名称'),
    array('ProductsNumber','Số sản phẩm','Products Number','제품 번호','产品编号'),
    array('ProductsDescription','sản phẩm Mô tả','Products Description','제품 설명','产品介绍'),
    array('ProductsOption','sản phẩm Tùy chọn','Products Option','제품 옵션','产品选项'),
    array('ProductsCreateDate','Sản phẩm Tạo ngày','Products Create Date','제품 생성 날짜','产品创建日期'),
    array('ProductsUpdateDate','Sản phẩm Cập nhật ngày','Products Update Date','제품 업데이트 날짜','产品更新日期'),
    array('Edit','Biên tập','Edit','편집하다','编辑'),
    array('LangId','Id ngôn ngữ','Language Id','언어 아이디','语言ID'),
    array('LangName','Tên ngôn ngữ','Language Name','언어 이름','语言名称'),
    array('LangVi','ngôn ngữ Vi','Language Vi','언어 바이올렛','语言六'),
    array('LangEn','Ngôn ngữ: Việt Nam','Language En','언어 : English','语言EN'),
    array('LangCn','ngôn ngữ Cn','Language Cn','언어 내지 Cn','语言简体'),
    array('LangKr','ngôn ngữ Kr','Language Kr','언어 Kr을','语言氪'),
    array('LangOption','ngôn ngữ Tùy chọn','Language Option','언어 옵션','语言选项'),
    array('LangCreateDate','Ngôn ngữ Tạo ngày','Language Create Date','언어는 생성 날짜','语言创建日期'),
    array('LangUpdateDate','Ngôn ngữ Cập nhật ngày','Language Update Date','언어 업데이트 날짜','语言更新日期'),
    array('Users','người dùng','Users','사용자','用户'),
    array('Lang','ngôn ngữ','Language','언어','语言'),
    array('Company','Công ty','Company','회사','公司'),
    array('Divisions','chia rẽ','Divisions','사단','分部'),
    array('Teams','Đội','Teams','팀','小组'),
    array('Parts','Các bộ phận','Parts','부속','部分'),
    array('Section','Phần','Section','부분','部分'),
    array('AssemblyLine','Dây chuyền lắp ráp','Assembly Line','조립 라인','流水线'),
    array('Stations','trạm','Stations','역','站'),
    array('Machines','máy móc','Machines','기계','机'),
    array('Models','mô hình','Models','모델','楷模'),
    array('Shift','sự thay đổi','Shift','시프트','转移'),
    array('Times','thời gian','Times','타임스','时'),
    array('TraceStation','Trạm dấu vết','Trace Station','추적 역','跟踪站'),
    array('TraceRoute','trace Route','Trace Route','경로 추적','跟踪路由'),
    array('TraceRouteAssign','Trace Route Gán','Trace Route Assign','추적 경로 지정','跟踪路由分配'),
    array('LabelType','Loại nhãn','Label Type','라벨 유형','标签类型'),
    array('LabelCode','nhãn Mã','Label Code','코드 레이블','标号码'),
    array('UserAssignTraceStation','Sử dụng Trạm vết Gán','User Assign Trace Station','사용자 지정 추적 역','用户分配跟踪站'),
    array('LabelCodeId','Nhãn Id Mã','Label Code Id','코드 ID 라벨','标号码标识'),
    array('LabelCodeName','Nhãn Code Name','Label Code Name','코드 이름 레이블','标签代码名称'),
    array('LabelCodeInformation','Nhãn Thông tin Mã','Label Code Information','코드 정보 레이블','标号码信息'),
    array('LabelCodeDescription','Nhãn Mã hàng Mô tả','Label Code Description','라벨 코드 설명','标签代码描述'),
    array('LabelCodeOption','Nhãn Mã Tùy chọn','Label Code Option','라벨 코드 옵션','标签代码选项'),
    array('LabelCodeCreateDate','Nhãn Mã Tạo ngày','Label Code Create Date','생성 날짜 코드 레이블','标号码创建日期'),
    array('LabelCodeUpdateDate','Nhãn Mã Cập nhật ngày','Label Code Update Date','코드 업데이트 날짜 레이블','标号码更新日期'),
    array('TraceStationId','Id truy xuất nguồn gốc Trạm','Traceability Station Id','추적 스테이션 ID','可追溯性站标识'),
    array('TraceStationName','Truy xuất nguồn gốc Trạm Tên','Traceability Station Name','추적 역 이름','可追溯性站名'),
    array('TraceStationInformation','Truy xuất nguồn gốc thông tin Trạm','Traceability Station Information','추적 역 정보','可追溯性信息站'),
    array('TraceStationDescription','Trạm truy xuất nguồn gốc Mô tả','Traceability Station Description','추적 역 설명','可追溯性站说明'),
    array('TraceStationOption','Trạm truy xuất nguồn gốc Tùy chọn','Traceability Station Option','추적 역 옵션','可追溯性站选项'),
    array('TraceStationCreateDate','Truy xuất nguồn gốc Trạm Tạo ngày','Traceability Station Create Date','추적 역 생성 날짜','可追溯性站创建日期'),
    array('TraceStationUpdateDate','Truy xuất nguồn gốc Trạm Cập nhật ngày','Traceability Station Update Date','추적 역 업데이트 날짜','可追溯性站更新日期'),
    array('TraceRouteId','Id Route truy xuất nguồn gốc','Traceability Route Id','추적 경로 아이디','可追溯性路由标识'),
    array('TraceRouteName','Truy xuất nguồn gốc Route Tên','Traceability Route Name','추적 경로 이름','可追溯性路由名称'),
    array('TraceRouteInformation','Truy xuất nguồn gốc thông tin Route','Traceability Route Information','추적 경로 정보','可追溯性路由信息'),
    array('TraceRouteDescription','Truy xuất nguồn gốc Route Mô tả','Traceability Route Description','추적 경로 설명','可追溯性路线说明'),
    array('TraceRouteOption','Truy xuất nguồn gốc Route Tùy chọn','Traceability Route Option','추적 경로 옵션','可追溯性路由选项'),
    array('TraceRouteCreateDate','Truy xuất nguồn gốc Route Tạo ngày','Traceability Route Create Date','추적 경로는 생성 날짜','可追溯性路线创建日期'),
    array('TraceRouteUpdateDate','Truy xuất nguồn gốc Route Cập nhật ngày','Traceability Route Update Date','추적 경로 업데이트 날짜','可追溯性路由更新日期'),
    array('Home','Trang Chủ','Home','집','家'),
    array('Productivity','Năng suất','Productivity','생산력','生产率'),
    array('Quantity','Định lượng','Quantity','수량','数量'),
    array('PartName','phần Name','Part Name','부품 이름','零件名称'),
    array('PartNumber','Part Number','Part Number','부품 번호','零件号'),
    array('Cavity','Lỗ','Cavity','공동','空穴'),
    array('Date','Ngày','Date','데이트','日期'),
    array('Lot','Nhiều','Lot','제비','批量'),
    array('Submit','Gửi đi','Submit','제출','提交'),
    array('PrintLabel','in tem','In tem','편에서','在TEM'),
    array('ProductInformation','Thông tin sản phẩm','Product Information','제품 정보','产品信息'),
    array('LinePatrol','dòng Patrol','Line Patrol','라인 순찰대','巡线'),
    array('FactoryIssuesReport','Báo cáo vấn đề nhà máy','Factory Issues Report','공장 문제 보고서','工厂问题报告'),
    array('QualityReport','Báo cáo chất lượng','Quality Report','품질 보고서','质量报告'),
    array('PushQaIssuesAlert','Đẩy Qa vấn đề Alert','Push Qa Issues Alert','품질 문제 경고를 밀어','按质量检查问题警报'),
    array('SparePart','Phụ tùng','Spare Part','예비 부','零部件'),
    array('Documents','Các tài liệu','Documents','서류','文件'),
    array('Bom,Iso,Ppap','Bom, Iso, PPAP','Bom, Iso, Ppap','그랬지, ISO, PPAP','汜，ISO，PPAP'),
    array('Profile','Hồ sơ','Profile','프로필','轮廓'),
    array('Settings','Cài đặt','Settings','설정','设置'),
    array('ActivityLogs','hoạt động Logs','Activity Logs','활동 로그','活动日志'),
    array('Logout','Đăng xuất','Logout','로그 아웃','登出'),
    array('Employees','người lao động','Employees','종업원 수','雇员'),
    array('EmployeeInformation','Thông tin nhân viên','Employee Information','직원 정보','员工信息'),
    array('Admin','quản trị viên','Admin','관리자','管理员'),
    array('AdminSeting','quản trị seting','Admin Seting','관리자 최저치를','管理员塞汀'),
    array('Modules','modules','Modules','모듈','模块'),
    array('Access','Truy cập','Access','접속하다','访问'),
    array('HallaElectronicsVina','Halla Vina Điện tử','Halla Electronics Vina','한라 전자 비나','汉拿电子维娜'),
    array('ModulesId','Id modules','Modules Id','모듈 아이디','模块标识'),
    array('ModulesName','modules Tên','Modules Name','모듈 이름','模块名称'),
    array('ModulesInformation','Thông tin modules','Modules Information','모듈 정보','模块的信息'),
    array('ModulesDescription','modules Mô tả','Modules Description','모듈 설명','模块说明'),
    array('ModulesOption','modules Tùy chọn','Modules Option','모듈 옵션','模块选项'),
    array('ModulesCreateDate','Modules Tạo ngày','Modules Create Date','모듈은 생성 날짜','模块创建日期'),
    array('ModulesUpdateDate','Modules Cập nhật ngày','Modules Update Date','모듈 업데이트 날짜','模块更新日期'),
    array('AccessId','Id truy cập','Access Id','접속 아이디','访问ID'),
    array('AccessOption','truy cập Tùy chọn','Access Option','액세스 옵션','访问选项'),
    array('AccessCreateDate','Truy cập Tạo ngày','Access Create Date','액세스 날짜를 만들기','访问创建日期'),
    array('AccessUpdateDate','Truy cập Cập nhật ngày','Access Update Date','액세스 업데이트 날짜','访问更新日期'),
    array('Print','In & Trace','Print & Trace','인쇄 및 추적','打印和跟踪'),
    array('Product','sản phẩm','Product','생성물','产品'),
    array('AddMaterial','Thêm Material','Add Material','재질 추가','添加材料'),
    array('Bom','Bom','Bom','BOM','汜'),
    array('Material','Vật chất','Material','재료','材料'),
    array('MaterialName','Tên sản phẩm','Material Name','소재 이름','材料名称'),
    array('MaterialCode','Mã vật liệu','Material Code','재질 코드','物料代码'),
    array('MaterialDescription','Mô tả Chất liệu','Material Description','자료 설명','材质说明'),
    array('Model','Mô hình','Model','모델','模型'),
    array('AddPicture','Thêm ảnh','Add Picture','사진 추가','添加图片'),
    array('MaterialType','Loại vật liệu','Material Type','자료 유형','材料类型'),
    array('MaterialTypesId','Id loại nguyên liệu','Material Types Id','원자재 유형의 아이디','材料类型标识'),
    array('MaterialTypesName','Các loại nguyên liệu Tên','Material Types Name','원자재 유형 이름','材料类型名称'),
    array('MaterialTypesCreateDate','Các loại tài liệu Tạo ngày','Material Types Create Date','원자재 유형은 생성 날짜','材料类型创建日期'),
    array('MaterialTypesUpdateDate','Các loại nguyên liệu Cập nhật ngày','Material Types Update Date','원자재 유형 업데이트 날짜','材料类型更新日期'),
    array('ProductName','tên sản phẩm','Product Name','상품명','产品名称'),
    array('ProductCode','Mã sản phẩm','Product Code','제품 코드','产品代码'),
    array('ProductDescription','Mô tả Sản phẩm','Product Description','제품 설명','产品描述'),
    array('ProductOption','Lựa chọn sản phẩm','Product Option','제품 옵션','产品选购'),
    array('EditPicture','Chỉnh sửa hình ảnh','Edit Picture','그림 편집','编辑图片'),
    array('QulityList','qulity Danh sách','Qulity List','QULITY 목록','表里如一名单'),
    array('Quality','Chất lượng','Quality','품질','质量'),
    array('QualityIssueControl','Kiểm soát chất lượng Issue','Quality Issue Control','품질 문제 제어','质量控制问题'),
    array('AddIssue','Thêm Issue','Add Issue','추가 문제','添加问题'),
    array('IssueList','Danh sách vấn đề','Issue List','문제 목록','问题列表'),
    array('FindIssue','Tìm Issue','Find Issue','찾기 문제','查找问题'),
    array('Report','Báo cáo','Report','보고서','报告'),
    array('IssueDate','ngày phát hành','Issue Date','발행일','发行日期'),
    array('Title','Tiêu đề','Title','표제','标题'),
    array('ScmObject','scm Object','Scm Object','SCM 개체','SCM对象'),
    array('LotNo','lô','Lot No','부지 없음','批号'),
    array('ProductionDate','Ngay san xuat','Production Date','생산 날짜','生产日期'),
    array('LotQuantity','lô Số lượng','Lot Quantity','부지의 수량','地块数量'),
    array('NgQuantity','ng Số lượng','Ng Quantity','잉 수량','吴数量'),
    array('TimeOccurs','Hiện Xảy ra','Time Occurs','시간 발생','时有发生'),
    array('DocNo','doc Không','Doc No','문서 번호','文件编号'),
    array('DueDate','Ngày đáo hạn','Due Date','마감일','截止日期'),
    array('FinishDate','Kết thúc ngày','Finish Date','마침 날짜','完成日期'),
    array('Pic','Pic','Pic','그림','PIC'),
    array('DefectContent','Defect Content','Defect Content','결함 내용','不良内容'),
    array('RootCause','Nguyên nhân gốc','Root Cause','근본 원인','根本原因'),
    array('Action','Hoạt động','Action','동작','行动'),
    array('IssuePicture','Issue Ảnh','Issue Picture','문제 사진','问题图片'),
    array('IssueReport','báo cáo vấn đề','Issue Report','문제 신고','问题报告'),
    array('Status','Trạng thái','Status','상태','状态'),
    array('Object','Vật','Object','목적','宾语'),
    array('DefectiveContent','Nội dung khiếm khuyết','Defective Content','결함 내용','瑕疵内容'),
    array('Picture','Hình ảnh','Picture','그림','图片'),
    array('QualityIssuelistDate','Chất lượng Issuelist ngày','Quality Issuelist Date','품질 Issuelist 날짜','质量Issuelist日期'),
    array('Lot Qty','lô Số lượng','Lot Qty','많은 수량','地块数量'),
    array('NgQty','ng Số lượng','Ng Qty','잉 수량','吴数量'),
    array('NgRate','ng Rate','Ng Rate','응 속도','不良率'),
    array('Doing','Đang làm','Doing','하기','干'),
    array('Schedule','lịch trình','Schedule','시간표','时间表'),
    array('Done','Làm xong','Done','끝난','完成'),
    array('Creator','Người sáng tạo','Creator','창조자','创造者'),
    array('DefectQuantity','Defect Số lượng','Defect Quantity','결함 수량','缺陷数量'),
    array('DefectRate','khiếm khuyết Rate','Defect Rate','불량률','缺陷率'),
    array('ScheduleDate','lịch ngày','Schedule Date','예약 날짜','计划日期'),
    array('ReportFile','Report file','Report File','보고서 파일','报告文件'),
    array('tables_SupplyChainType','tables_ Supply Chain Loại','tables_ Supply Chain Type','tables_ 공급 체인 유형','tables_供应链类型'),
    array('SupplyChainType','Cung cấp Loại Chain','Supply Chain Type','공급 체인 유형','供应链类型'),
    array('SupplyChainTypeId','Id Loại Supply Chain','Supply Chain Type Id','공급 체인 유형 ID','供应链类型标识'),
    array('SupplyChainTypeName','Supply Chain Loại Tên','Supply Chain Type Name','공급 체인 유형 이름','供应链类型名称'),
    array('SupplyChainTypeOption','Supply Chain Loại Tùy chọn','Supply Chain Type Option','공급 체인 유형 옵션','供应链类型选项'),
    array('SupplyChainTypeCreateDate','Supply Chain Loại Tạo ngày','Supply Chain Type Create Date','공급 체인 유형 생성 날짜','供应链类型创建日期'),
    array('SupplyChainTypeUpdateDate','Supply Chain Loại Cập nhật ngày','Supply Chain Type Update Date','공급 체인 유형 업데이트 날짜','供应链类型更新日期'),
    array('SupplyChainObject','Supply Chain Object','Supply Chain Object','공급망 개체','供应链对象'),
    array('SupplyChainObjectId','Id Chain Object cung cấp','Supply Chain Object Id','공급 체인 개체 ID','供应链的对象ID'),
    array('SupplyChainObjectName','Supply Chain Tên đối tượng','Supply Chain Object Name','공급망 개체 이름','供应链对象名称'),
    array('SupplyChainObjectOption','Supply Chain Object Tùy chọn','Supply Chain Object Option','공급 체인 개체 옵션','供应链实物期权'),
    array('SupplyChainObjectCreateDate','Supply Chain Object Tạo ngày','Supply Chain Object Create Date','공급망 개체 생성 날짜','供应链对象创建日期'),
    array('SupplyChainObjectUpdateDate','Supply Chain Object Cập nhật ngày','Supply Chain Object Update Date','공급망 개체 업데이트 날짜','供应链对象更新日期'),
    array('SupplyChain','Chuỗi cung ứng','Supply Chain','공급망','供应链'),
    array('Delay','Sự chậm trễ','Delay','지연','延迟'),
    array('ProductList','Danh sách sản phẩm','Product List','상품 목록','产品列表'),
    array('BomList','Bom Danh sách','Bom List','BOM 목록','BOM清单'),
    array('AddBom','Thêm Bom','Add Bom','BOM이 추가','添加汜'),
    array('BomsDirectParent','Chánh BOMs Direct','Boms Direct Parent','BOM을 직접 부모','物料清单直接父'),
    array('BomsPartNo','BOMs Phần Không','Boms Part No','BOM의 부품 번호','物料清单部件号'),
    array('BomsPartName','BOMs Phần Name','Boms Part Name','BOM의 부품 이름','材料明细表零件名称'),
    array('BomsSize','BOMs Kích','Boms Size','BOM의 크기','物料清单尺寸'),
    array('BomsNet','BOMs Net','Boms Net','BOM을 순','物料清单网'),
    array('BomsGloss','BOMs Gloss','Boms Gloss','BOM의 광택','光泽的材料明细表'),
    array('BomsMaterial','BOMs Material','Boms Material','BOM을 재료','材料明细表材料'),
    array('BomsUnit','BOMs Unit','Boms Unit','BOM의 단위','材料明细表单位'),
    array('BomsQty','BOMs Số lượng','Boms Qty','BOM의 수량','物料清单数量'),
    array('BomsProcess','BOMs Process','Boms Process','BOM을 프로세스','物料清单过程'),
    array('BomsMaker','BOMs maker','Boms Maker','BOM을 메이커','BOM表制作'),
    array('BomsClassifiedMaterial','BOMs Phân loại Vật liệu','Boms Classified Material','BOM에 재질 분류','物料清单机密材料'),
    array('BomsMachine','BOMs Máy','Boms Machine','BOM을 기계','材料明细表机'),
    array('AddProduct','Thêm sản phẩm','Add Product','제품 추가','添加产品'),
    array('ProductsSize','sản phẩm Kích','Products Size','제품 크기','产品尺寸'),
    array('Boms','BOMs','Boms','BOM을','物料清单'),
    array('ProductNumber','Số sản phẩm','Product Number','제품 번호','产品编号'),
    array('ProductSize','Kích thước sản phẩm','Product Size','제품 크기','产品尺寸'),
    array('ProductNet','Sản phẩm Net','Product Net','제품 순','产品网'),
    array('ProductGloss','Gloss sản phẩm','Product Gloss','제품 광택','产品光泽度'),
    array('ProductMaterial','Chất liệu sản phẩm','Product Material','제품 소재','产品材质'),
    array('ProductUnit','Đơn vị sản phẩm','Product Unit','제품 단위','产品单位'),
    array('TraceRouteAssignId','Id Gán traceroute','Trace Route Assign Id','추적 경로 지정 아이디','跟踪路由给ID'),
    array('TraceRouteAssignDescription','Trace Route Gán Mô tả','Trace Route Assign Description','추적 경로 지정 설명','跟踪路由分配说明'),
    array('TraceRouteAssignOption','Trace Route Gán Tùy chọn','Trace Route Assign Option','추적 경로 지정 옵션','跟踪路由分配方案'),
    array('TraceRouteAssignCreateDate','Trace Route Gán Tạo ngày','Trace Route Assign Create Date','추적 경로 지정 날짜 만들기','跟踪路由分配创建日期'),
    array('TraceRouteAssignUpdateDate','Trace Route Gán Cập nhật ngày','Trace Route Assign Update Date','추적 경로 지정 업데이트 날짜','跟踪路由分配更新日期'),
    array('LabelTypeId','Nhãn Id Loại','Label Type Id','유형 ID 라벨','标签类型ID'),
    array('LabelTypeName','Nhãn Loại Tên','Label Type Name','유형 이름을 레이블','标签类型名称'),
    array('LabelTypeInformation','Nhãn Loại thông tin','Label Type Information','유형 정보를 라벨','标签类型信息'),
    array('LabelTypeDescription','Loại nhãn Mô tả','Label Type Description','라벨 유형 설명','标签类型说明'),
    array('LabelTypeOption','Loại nhãn Tùy chọn','Label Type Option','라벨 유형 옵션','标签类型选项'),
    array('LabelTypeCreateDate','Nhãn Loại Tạo ngày','Label Type Create Date','생성 날짜를 입력 레이블','标签类型创建日期'),
    array('LabelTypeUpdateDate','Nhãn Loại Cập nhật ngày','Label Type Update Date','유형 업데이트 날짜 레이블','标签类型更新日期'),
    array('ProductsNet','sản phẩm Net','Products Net','제품 순','产品网'),
    array('ProductsGloss','sản phẩm Gloss','Products Gloss','제품 광택','产品光泽度'),
    array('ProductsMaterial','sản phẩm Nguyên liệu','Products Material','제품 소재','产品材质'),
    array('ProductsUnit','sản phẩm Đơn vị','Products Unit','제품 단위','出品单位'),
    array('SetStationLabelRules','Establish mẫu tem','Thiết lập mẫu tem','티엣 무릎 MAU 편','切一圈MAU TEM'),
    array('Id','Tôi','Id','신분증','ID'),
    array('Station','Ga tàu','Station','역','站'),
    array('LabelPattern','nhãn Pattern','Label Pattern','레이블 패턴','标签模式'),
    array('LastUpdate','Cập nhật cuối cùng','Last Update','마지막 업데이트','最后更新'),
    array('LabelList','LabelList','LabelList','LabelList','LabelList'),
    array('PackingStandard','đóng gói tiêu chuẩn','Packing Standard','표준 포장','包装标准'),
    array('LabelHistory','Lịch sử nhãn','Label History','라벨의 역사','标签历史'),
    array('LabelValue','nhãn Giá trị','Label Value','레이블 값','标签值'),
    array('Ok','Đồng ý','Ok','확인','好'),
    array('Ng','ng','Ng','잉','伍'),
    array('Processes','Processes','Processes','프로세스','流程'),
    array('Makers','Makers','Makers','업체','庄家'),
    array('ClassifiedMaterials','Vật vặt','Classified Materials','분류 된 재료','分类材料'),
    array('BillOfMaterials','Hóa đơn nguyên vật liệu','Bill Of Materials','재료의 빌','材料清单'),
    array('AddProcess','Thêm Process','Add Process','추가 프로세스','添加进程'),
    array('ProcessesId','xử lý Id','Processes Id','이드 처리','流程标识'),
    array('ProcessesName','xử lý Tên','Processes Name','이름 처리','流程名称'),
    array('ProcessesDescription','Processes Mô tả','Processes Description','프로세스 설명','流程说明'),
    array('AddMaker','Thêm maker','Add Maker','추가 메이커','添加设备'),
    array('MakersId','Id Makers','Makers Id','업체 아이디','厂商标识'),
    array('MakersName','Makers Tên','Makers Name','업체 이름','制造商名称'),
    array('MakersDescription','Makers Mô tả','Makers Description','업체 설명','说明庄家'),
    array('AddClassifiedMaterial','Thêm Material vặt','Add Classified Material','분류 된 자료를 추가','添加机密材料'),
    array('ClassifiedMaterialsId','Id Vật vặt','Classified Materials Id','분류 된 재료 아이디','分类材料标识'),
    array('ClassifiedMaterialsName','Vặt Vật liệu Tên','Classified Materials Name','분류 된 재료 이름','分类材料名称'),
    array('ClassifiedMaterialsDescription','Vặt Vật liệu Mô tả','Classified Materials Description','분류 된 자료 설명','分类材料说明'),
    array('AddMachine','Thêm Machine','Add Machine','기계 추가','添加计算机'),
    array('Index','Mục lục','Index','인덱스','指数'),
    array('Search','Tìm kiếm','Search','검색','搜索'),
    array('PrintAndTraceability','In Và Truy xuất nguồn gốc','Print And Traceability','그리고 추적을 인쇄','打印和可追溯性'),
    array('RoutingList','Routing Danh sách','Routing List','라우팅 목록','路由表'),
    array('Dc','dc','Dc','DC','DC'),
    array('Nc','nc','Nc','체크 안함','数控'),
    array('St','St','St','성','圣'),
    array('Fi','Fi','Fi','인터넷','网络连接'),
    array('BomLists','Danh sách Bom','Bom Lists','BOM 목록','BOM清单'),
    array('SparePartCategories','Tùng Phần Categories','Spare Part Categories','예비 부품 카테고리','备件分类'),
    array('StartDate','ngày bắt đầu','Start Date','시작 날짜','开始日期'),
    array('EndDate','Ngày cuối','End Date','종료 날짜','结束日期'),
    array('BomlistsInfo','Bomlists Thông tin','Bomlists Info','Bomlists 정보','Bomlists信息'),
    array('Add new BOM','Thêm B mới O M','Add new B O M','새로운 B O M 추가','添加新的B○中号'),
    array('Process','Quá trình','Process','방법','处理'),
    array('Maker','nhà sản xuất','Maker','만드는 사람','制作者'),
    array('ClassifiedMaterial','Chất liệu vặt','Classified Material','분류 된 재료','密件'),
    array('Machine','Máy móc','Machine','기계','机'),
    array('acq30002201','acq30002201','acq30002201','acq30002201','acq30002201'),
    array('ProductsEngName','Sản phẩm Eng Name','Products Eng Name','제품 영어 이름','产品名称英'),
    array('ProductsStock','sản phẩm Cổ','Products Stock','제품 증권','产品库存'),
    array('ProductsSafetyStk','Sản phẩm An toàn STK','Products Safety Stk','제품 안전 STK','产品安全STK'),
    array('CategoriesName','Categories Tên','Categories Name','카테고리 이름','分类名称'),
    array('AddCategory','thêm thể loại','Add Category','추가 카테고리','添加类别'),
    array('CategoriesId','Id loại','Categories Id','카테고리 아이디','分类标识'),
    array('PartNo','phần Không','Part No','부품 번호','部件号'),
    array('EngName','Eng Name','Eng Name','영어 이름','工程名称'),
    array('Description','Sự miêu tả','Description','기술','描述'),
    array('Unit','Đơn vị','Unit','단위','单元'),
    array('NumberInStock','Số Còn hàng','Number In Stock','수에서 증권','库存数量'),
    array('SafetyStk','an toàn STK','Safety Stk','안전 STK','安全STK'),
    array('MinimumStk','tối thiểu STK','Minimum Stk','최소 STK','最小STK'),
    array('Location','Vị trí','Location','위치','位置'),
    array('Category','thể loại','Category','범주','类别'),
    array('OrderStatus','Tình trạng đặt hàng','Order Status','주문 상태','订单状态'),
    array('Note','Ghi chú','Note','노트','注意'),
    array('EnglishName','Tên tiêng Anh','English Name','영어 이름','英文名'),
    array('acq30033201','acq30033201','acq30033201','acq30033201','acq30033201'),
    array('Input list','danh mục đầu vào','Input list','입력 목록','输入列表'),
    array('ImportsDate','nhập khẩu ngày','Imports Date','수입 날짜','进口日期'),
    array('ProductsQty','sản phẩm Số lượng','Products Qty','제품 수량','产品数量'),
    array('ProductsUnitPrice','Sản phẩm Đơn giá','Products Unit Price','제품 단가','产品单价'),
    array('ImportsNote','nhập khẩu Note','Imports Note','수입 참고','进口注'),
    array('Output list','danh mục đầu ra','Output list','출력 목록','输出列表'),
    array('ExportsDate','Xuất khẩu ngày','Exports Date','수출 날짜','出口日期'),
    array('ExportsReason','Xuất khẩu Reason','Exports Reason','수출 이유','出口原因'),
    array('ExportsNote','Xuất khẩu Note','Exports Note','수출 주','注出口'),
    array('Import history','lịch sử nhập khẩu','Import history','가져 오기 역사','进口历史'),
    array('ImportsPO','Nhập khẩu P O','Imports P O','수입 P O','进口P 2 O'),
    array('Export history','lịch sử xuất khẩu','Export history','수출 역사','出口历史'),
    array('ExportsPO','Xuất khẩu P O','Exports P O','P O 수출','出口P 2 O'),
    array('ExportsReceiver','Xuất khẩu Receiver','Exports Receiver','수출 수신기','出口接收器'),
    array('Areas','Khu vực','Areas','지역','地区'),
    array('MemoReduce','Memo Giảm','Memo Reduce','메모 감소','备注减少'),
    array('MemoApplicability','Memo Khả năng áp dụng','Memo Applicability','메모 적용','备注适用性'),
    array('Memos','bản ghi nhớ','Memos','메모','备忘录'),
    array('ProductsLocation','sản phẩm Location','Products Location','제품 위치','产品定位'),
    array('AddSupplier','Add Nhà cung cấp','Add Supplier','추가 공급','添加供应商'),
    array('ImportsDocNo','Nhập khẩu Doc Không','Imports Doc No','수입 문서 번호','进口文件编号'),
    array('ExportsDocNo','Xuất khẩu Doc Không','Exports Doc No','문서 번호는 수출','出口文件编号'),
    array('AddSection','Thêm Mục','Add Section','섹션 추가','添加章节'),
    array('Supplier Name','tên đệm','Supplier Name','공급 업체 이름','供应商名称'),
    array('UpdateImport','cập nhật nhập','Update Import','업데이트 가져 오기','更新导入'),
    array('Month','tháng','Month','달','月'),
    array('Ton','tấn','Ton','톤','吨'),
    array('AddMemos','Thêm bản ghi nhớ','Add Memos','메모 추가','添加备忘录'),
    array('MemosList','bản ghi nhớ Danh sách','Memos List','메모 목록','记事列表'),
    array('FindMemos','Tìm bản ghi nhớ','Find Memos','메모 찾기','查找备忘录'),
    array('MemoSuggestion','Memo Đề xuất','Memo Suggestion','메모 제안','备忘录建议'),
    array('Dept','Phòng','Dept','부서','部门'),
    array('Area','Khu vực','Area','지역','区域'),
    array('Efficiency','hiệu quả','Efficiency','능률','效率'),
    array('ResultOfReview','Kết quả đánh giá','Result Of Review','검토 결과','结果回顾'),
    array('Plan','Kế hoạch','Plan','계획','计划'),
    array('MemosIssue','bản ghi nhớ Issue','Memos Issue','메모 문제','发行备忘录'),
    array('MemosImprovementContent','Nội dung bản ghi nhớ cải thiện','Memos Improvement Content','메모 개선 내용','备忘录内容的改进'),
    array('MemosEfficiency','bản ghi nhớ hiệu quả','Memos Efficiency','메모 효율성','备忘录效率'),
    array('ApplyDate','ngày Áp Dụng','Apply Date','날짜 적용','申请日期'),
    array('MemosPicture','bản ghi nhớ Hình ảnh','Memos Picture','메모 사진','备忘录图片'),
    array('MemosReport','bản ghi nhớ Report','Memos Report','메모 보고서','备忘录报告'),
    array('MemoReduceId','Memo Giảm Id','Memo Reduce Id','메모 이드 감소','备注减少标识'),
    array('MemoReduceName','Memo Giảm Tên','Memo Reduce Name','메모 이름 감소','备注减少名称'),
    array('MemoReduceDescription','Memo Giảm Mô tả','Memo Reduce Description','메모 설명 감소','备注减少说明'),
    array('MemoReduceOption','Memo Giảm Tùy chọn','Memo Reduce Option','메모 옵션을 줄','备注减少选项'),
    array('MemoReduceCreateDate','Memo Giảm Tạo ngày','Memo Reduce Create Date','메모 날짜를 만들기 감소','备注减少创建日期'),
    array('MemoReduceUpdateDate','Memo Giảm Cập nhật ngày','Memo Reduce Update Date','메모 업데이트 날짜 감소','备注减少更新日期'),
    array('MemoApplicabilityId','Id áp dụng Memo','Memo Applicability Id','메모 적용 아이디','备注适用性标识'),
    array('MemoApplicabilityName','Memo Tên Khả năng áp dụng','Memo Applicability Name','메모 적용 이름','备注适用性名称'),
    array('MemoApplicabilityDescription','Memo áp dụng Mô tả','Memo Applicability Description','메모 적용 설명','备注适用性说明'),
    array('MemoApplicabilityOption','Memo áp dụng Tùy chọn','Memo Applicability Option','메모 적용 옵션','备注适用性选项'),
    array('MemoApplicabilityCreateDate','Memo áp dụng Tạo ngày','Memo Applicability Create Date','메모 적용 날짜를 만들기','备注适用性创建日期'),
    array('MemoApplicabilityUpdateDate','Memo áp dụng Cập nhật ngày','Memo Applicability Update Date','메모 적용 업데이트 날짜','备注适用性更新日期'),
    array('EmployeesName','Tên nhân viên','Employees Name','종업원 이름','员工的名字'),
    array('EmployeesCode','Nhân viên Mã','Employees Code','종업원 코드','员工守则'),
    array('EmployeesPosition','nhân viên Chức vụ','Employees Position','종업원 위치','员工职位'),
    array('Add new employee','Thêm nhân viên mới','Add new employee','신입 사원 추가','添加新员工'),
    array('EmployeesFirstName','Tên nhân viên','Employees First Name','종업원 이름','员工名字'),
    array('EmployeesLastName','Nhân viên Họ','Employees Last Name','종업원 성','员工姓'),
    array('EmployeesEmail','Email nhân viên','Employees Email','직원 이메일','员工电子邮件'),
    array('Division','phân công','Division','분할','师'),
    array('Team','Đội','Team','팀','球队'),
    array('Positions','vị trí','Positions','포지션','位置'),
    array('AddPosition','Thêm Chức vụ','Add Position','추가 위치','添加位置'),
    array('PositionsId','Id vị trí','Positions Id','포지션 아이디','位置标识'),
    array('PositionsName','vị trí Tên','Positions Name','포지션 이름','职位名称'),
    array('Add new position','Thêm vị trí mới','Add new position','새 위치 추가','添加新的位置'),
    array('AddTeam','Thêm đội','Add Team','팀 추가','加入团队'),
    array('Add new team','Thêm nhóm mới','Add new team','새로운 팀 추가','添加新的团队'),
    array('Sections','phần','Sections','섹션','第'),
    array('MemosContent','bản ghi nhớ nội dung','Memos Content','메모 내용','备忘录内容'),
    array('MemosCreator','bản ghi nhớ Đấng tạo Hóa','Memos Creator','메모 작성자','备忘录造物主'),
    array('MemosPic','bản ghi nhớ Pic','Memos Pic','메모 그림','备忘录产品图'),
    array('MemosApplyDate','Bản ghi nhớ Ngày Áp Dụng','Memos Apply Date','메모 날짜 적용','备忘录申请日期'),
    array('ApplyStatus','Áp dụng Tình trạng','Apply Status','상태 적용','应用现状'),
    array('UpdatePicture','cập nhật hình ảnh','Update Picture','업데이트 사진','更新图片'),
    array('UpdateFile','cập nhật tập tin','Update File','업데이트 파일','更新文件'),
    array('Update','cập nhật','Update','최신 정보','更新'),
    array('Edit employee','Sửa nhân viên','Edit employee','편집 직원','编辑员工'),
    array('UpdateOutput','cập nhật Output','Update Output','업데이트 출력','更新输出'),
    array('UpdateInput','cập nhật Input','Update Input','업데이트 입력','更新输入'),
    array('UpdateExport','cập nhật Xuất','Update Export','업데이트 내보내기','更新出口'),
    array('PatrolItems','Patrol Items','Patrol Items','경비 항목','巡警项目'),
    array('PatrolLosses','Thiệt hại Patrol','Patrol Losses','순찰 손실','巡逻损失'),
    array('ProductsMinimumStk','Sản phẩm tối thiểu STK','Products Minimum Stk','제품 최소 STK','产品最低STK'),
    array('ProductsCategory','danh mục sản phẩm','Products Category','제품 카테고리','产品分类'),
    array('ProductsOrderStatus','Tình trạng sản phẩm theo thứ tự','Products Order Status','제품 주문 상태','产品订单状态'),
    array('ProductsMachine','Máy sản phẩm','Products Machine','제품 기계','产品机'),
    array('ProductsNote','sản phẩm Note','Products Note','제품 참고','产品说明'),
    array('Hanmi','Hanmi','Hanmi','한미','韩美'),
    array('MonthlyReport','Báo cáo hàng tháng','Monthly Report','월별보고','月度报告'),
    array('Total','Toàn bộ','Total','합계','总'),
    array('TopReport','Lên trên báo cáo','Top Report','톱 보고서','热门报告'),
    array('TimesId','Id lần','Times Id','타임즈 아이디','时报标识'),
    array('TimesName','Times Tên','Times Name','타임스 이름','时报名称'),
    array('TimesInformation','Times Thông tin','Times Information','시간 정보','信息时报'),
    array('TimesDescription','Times Mô tả','Times Description','타임즈 설명','次详细说明'),
    array('TimesOption','Times Tùy chọn','Times Option','시간 옵션','次选'),
    array('Section report','báo cáo Mục','Section report','섹션 보고서','科报告'),
    array('YearlyReport','báo cáo hàng năm','Yearly Report','연간 보고서','年度报告'),
    array('ScoreBoard','điểm Board','Score Board','보드 점수','计分板'),
    array('PictureAfter','hình ảnh Sau','Picture After','사진 후','图片后'),
    array('Score','Ghi bàn','Score','점수','得分了'),
    array('LabelHistoryFi','Nhãn Lịch sử Fi','Label History Fi','역사 인터넷 레이블','标签历史网络'),
    array('LabelHistoryFi2','Nhãn Lịch sử Fi2','Label History Fi2','역사 FI2 레이블','标签历史FI2'),
    array('ReportFi2','báo cáo Fi2','Report Fi2','보고서 FI2','报告FI2'),
    array('PackingUnique','đóng gói độc đáo','Packing Unique','독특한 포장','独特的包装'),
    array('NotSet','Không được thiết lập','Not Set','하지 않음 설정','没有设置'),
    array('Yes','Đúng','Yes','예','是'),
    array('No','Không','No','아니','没有'),
    array('Yes - Not Trace','Có - Không Truy xuất nguồn gốc','Yes - Not Traceability','예 - 없음 추적','是 - 不可追溯性'),
    array('MemosScore','Điểm bản ghi nhớ','Memos Score','메모 점수','备忘录分数'),
    array('Top','Hàng đầu','Top','상단','最佳'),
    array('issue','vấn đề','issue','발행물','问题'),
    array('No.','Không.','No.','아니.','没有。'),
    array('AreasId','Id khu vực','Areas Id','지역 아이디','区域标识'),
    array('AreasName','khu vực Tên','Areas Name','지역 이름','地区名称'),
    array('AreasDescription','khu vực Mô tả','Areas Description','지역 설명','区域描述'),
    array('AreasOption','vùng Tùy chọn','Areas Option','지역 옵션','区选项'),
    array('AreasCreateDate','Khu vực Tạo ngày','Areas Create Date','지역은 날짜를 만들기','区创建日期'),
    array('AreasUpdateDate','Khu vực Cập nhật ngày','Areas Update Date','지역 업데이트 날짜','区更新日期'),
    array('ProductsInformation','Thông tin sản phẩm','Products Information','제품 정보','产品信息'),
    array('FactoryIssueReport','Nhà máy Báo cáo Issue','Factory Issue Report','공장 이슈 보고서','工厂问题报告'),
    array('Qbank','Q-Ngân hàng','Q-Bank','Q-은행','Q-银行'),
    array('ControlSparePart','Kiểm soát phụ tùng','Control Spare Part','제어 예비 부','控制备件'),
    array('Document','tài liệu','Document','문서','文献'),
    array('DocumentEx','Tài liệu Ex','Document Ex','문서 예','文件EX'),
    array('EmployeesInformation','Thông tin nhân viên','Employees Information','직원 정보','员工信息'),
    array('TraceStationPosition','Dấu vết Trạm Chức vụ','Trace Station Position','추적 역 위치','跟踪站的位置'),
    array('Wip','WIP','Wip','WIP','WIP'),
    array('Permission','sự cho phép','Permission','허가','允许'),
    array('UsersLang','người dùng Lang','Users Lang','사용자 랭','用户郎'),
    array('AddPlan','Thêm Plan','Add Plan','계획 추가','加入计划'),
    array('News','Tin tức','News','뉴스','新闻')
);

// $db = new db();

// foreach ($arr as $key => $value) {
// $sql = "UPDATE `lang` SET `LangVi`=?,`LangEn`=?,`LangCn`=?,`LangKr`=? WHERE `LangName` =?";
// $db -> query($sql,$value[1],$value[2],$value[4],$value[3],$value[0]);
// }

